usuarios.servicio.IServicioUsuarios=usuarios.servicio.ServicioUsuarios
usuarios.puertos.ManejadorEventos=usuarios.adaptadores.ManejadorEventosImpl
usuarios.puertos.PublicadorEventos=usuarios.adaptadores.PublicadorRabbitMQ
# RabbitMQ
rabbitmq.uri=amqps://finmzuhw:nJqWdRwr_FGN-osSFobELS0aNnzSQQvh@collie.lmq.cloudamqp.com/finmzuhw