usuarios.servicio.IServicioUsuarios=usuarios.servicio.ServicioUsuarios
usuarios.puertos.ManejadorEventos=usuarios.puertos.ManejadorEventosImpl
# RabbitMQ
rabbitmq.uri=amqps://finmzuhw:nJqWdRwr_FGN-osSFobELS0aNnzSQQvh@collie.lmq.cloudamqp.com/finmzuhw