usuarios.servicio.IServicioUsuarios=usuarios.servicio.ServicioUsuarios
usuarios.puertos.ManejadorEventos=usuarios.adaptadores.ManejadorEventosImpl
usuarios.puertos.PublicadorEventos=usuarios.adaptadores.PublicadorRabbitMQ
# RabbitMQ
rabbitmq.uri=amqp://guest:guest@localhost:5672