spring.application.name=compraventas
server.port=8083

# MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://<usuario>:<password>@<cluster>.mongodb.net/compraventas?retryWrites=true&w=majority

# URLs de microservicios externos
microservicio.productos.url=http://localhost:8080/productos-spring/
microservicio.usuarios.url=http://localhost:8081/usuarios/

# OpenAPI / Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html