segundamano.modelo.Usuario=segundamano.repositorio.RepositorioUsuariosAdHocJPA
segundamano.modelo.Categoria=segundamano.repositorio.RepositorioCategoriasAdHocJPA
segundamano.modelo.Producto=segundamano.repositorio.RepositorioProductosAdHocJPA

