server.port=8090
spring.application.name=pasarela
zuul.sensitiveHeaders=

# Usuarios está en puerto 8080 interno 
zuul.routes.usuarios.path=/usuarios/**
zuul.routes.usuarios.url=http://usuarios:8080/

# Productos
zuul.routes.productos.path=/productos/**
zuul.routes.productos.url=http://productos:9090/

# Compraventas
zuul.routes.compraventas.path=/compraventas/**
zuul.routes.compraventas.url=http://compraventas:8083/

# OAuth2 GitHub 
spring.security.oauth2.client.registration.github.client-id=Ov23liDripuCMzd99GGc
spring.security.oauth2.client.registration.github.client-secret=1ea4b589e0dc097269b0a67331ad32d130aabb80
spring.security.oauth2.client.registration.github.redirect-uri=https://organic-computing-machine-7v57q54qx9g9cr9gv-8090.app.github.dev/login/oauth2/code/github