server.port=8090
spring.application.name=pasarela
zuul.sensitiveHeaders=

# Usuarios está en puerto 8080 interno 
zuul.routes.usuarios.path=/usuarios/**
zuul.routes.usuarios.url=http://usuarios:8080/

# Productos
zuul.routes.productos.path=/productos/**
zuul.routes.productos.url=http://productos:9090/

# Compraventas
zuul.routes.compraventas.path=/compraventas/**
zuul.routes.compraventas.url=http://compraventas:8083/

# OAuth2 GitHub (pendienteee)!!
spring.security.oauth2.client.registration.github.client-id=TU_CLIENT_ID
spring.security.oauth2.client.registration.github.client-secret=TU_CLIENT_SECRET