spring.application.name=compraventas
server.port=8083

# MongoDB local
spring.data.mongodb.uri=mongodb://localhost:27017/compraventas

# URLs de microservicios externos
microservicio.productos.url=http://localhost:9090/
microservicio.usuarios.url=http://localhost:8080/

# OpenAPI / Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
spring.rabbitmq.addresses=amqps://finmzuhw:nJqWdRwr_FGN-osSFobELS0aNnzSQQvh@collie.lmq.cloudamqp.com/finmzuhw